<div class="body-content">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<h2> TAGS </h2>
						<p>
							Place all tags in here.
						</p>
					</div>
					<div class="col-sm-8">
						<h2> Live News/Blog Feed </h2>
						<p>
							Donec id elit non mi porta gravida at eget metus.
							Fusce dapibus, tellus ac cursus commodo, tortor
							mauris condimentum nibh, ut fermentum massa justo
							sit amet risus. Etiam porta sem malesuada magna
							mollis euismod. Donec sed odio dui.
						</p>
						<h2> Live News/Blog Feed </h2>
						<p>
							Donec id elit non mi porta gravida at eget metus.
							Fusce dapibus, tellus ac cursus commodo, tortor
							mauris condimentum nibh, ut fermentum massa justo
							sit amet risus. Etiam porta sem malesuada magna
							mollis euismod. Donec sed odio dui.
						</p>
						<h2> Live News/Blog Feed </h2>
						<p>
							Donec id elit non mi porta gravida at eget metus.
							Fusce dapibus, tellus ac cursus commodo, tortor
							mauris condimentum nibh, ut fermentum massa justo
							sit amet risus. Etiam porta sem malesuada magna
							mollis euismod. Donec sed odio dui.
						</p>
					</div>
					<div class="col-sm-2">
						<h2> Popular Stories </h2>
						<p>
							Most popular books etc here.
						</p>
					</div>
				</div>
			</div>
